version: 0.2
phases:
  build:
    commands:
      - echo "-------sam build statring...--------"
      - sam build -t SAM-test.yaml
      - echo "--------sam build finished----------"
      - echo "-------sam deploy statring...--------"
      - sam deploy --stack-name LambdaDeployStack --region ap-northeast-1 -t SAM-test.yaml --no-fail-on-empty-changeset
      - echo "--------sam deploy finished----------"
