Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: src/
      AutoPublishAlias: live
      DeploymentPreference: 
        Type: Canary10Percent10Minutes